"""Add manager model

Revision ID: 0249fd3fd296
Revises: 48776ab862f3
Create Date: 2026-08-19 16:00:37.965571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0249fd3fd296'
down_revision: Union[str, Sequence[str], None] = '48776ab862f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('manager_enterprise',
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.PrimaryKeyConstraint('manager_id', 'enterprise_id'),
    sa.UniqueConstraint('manager_id', 'enterprise_id', name='uq_manager_enterprise')
    )
    op.create_unique_constraint('uq_driver_vehicle', 'driver_vehicle', ['driver_id', 'vehicle_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_driver_vehicle', 'driver_vehicle', type_='unique')
    op.drop_table('manager_enterprise')
    op.drop_table('managers')
    # ### end Alembic commands ###
